# For more information, see https://aka.ms/vscode-remote/devcontainer
FROM mcr.microsoft.com/vscode/devcontainers/python:3

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>